### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nerrad**
Another quote

### CODE REVIEW

**Comment by AntJanus** [comment]
@nerrad can you rebase and resubmit? I love this one!

**Comment by nerrad** [comment]
rebased, should be good to go I think?

**Comment by AntJanus** [comment]
yep! Thanks! :)

**Comment by nerrad** [comment]
btw, don't know if you noticed but the missing period on the statement was _intentional_ because it fits with the statement ;)

**Comment by AntJanus** [comment]
Ha! Didn't notice. Perfect! :)

**Pull request merged**
